twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig'] # accepte plusieurs thèmes
    globals:
        navs: '@App\Twig\NavExtension'
        site:
            name: base
            description: 'App de base pour projet Symfony'
            order_contact: ''
            version: '1.0'
            desc: ''
            email: ''
            logo: ''
            logo_sidebar: ''
when@test:
    twig:
        strict_variables: true
